const TASKS_NUMBER = 20;
const DEFAULT_CARD_RENDER_NUMBER = 8;
const DAYS_IN_WEEK = 7;
const HOURS_IN_DAY = 24;
const MINUTES_IN_HOUR = 60;
const SECONDS_IN_MINUTE = 60;
const MSECONDS_IN_SECOND = 1000;
const MIN_TIME_RANGE = -1000000000;
const MAX_TIME_RANGE = 1000000000;

export {
  TASKS_NUMBER,
  DEFAULT_CARD_RENDER_NUMBER,
  DAYS_IN_WEEK,
  HOURS_IN_DAY,
  MINUTES_IN_HOUR,
  SECONDS_IN_MINUTE,
  MSECONDS_IN_SECOND,
  MIN_TIME_RANGE,
  MAX_TIME_RANGE
};
